export const INTEGRITY_SCHEMA_VERSION: "ruleoak.integrity.v1";
export function canonicalHash(value: unknown): string;
export function canonicalIntegrityPayload(value: unknown): string;
export function stripIntegrityFields(value: unknown): unknown;
export function generateEd25519KeyPair(): { publicKeyPem: string; privateKeyPem: string };
export function createTrustRoot(options?: object): object;
export function validateTrustRoot(trustRoot: object): { valid: boolean; errors: string[]; keyCount: number };
export function signPayload(value: unknown, options: { privateKeyPem: string; keyId?: string; signedAt?: string; purpose?: string }): object;
export function verifyPayloadSignature(value: unknown, signatureEnvelope: object, trustRoot: object): { valid: boolean; errors: string[]; payloadHash: string; keyId: string | null };
export function policyPackManifestHash(manifest: object): string;
export function createPolicyPackSignature(manifest: object, options: { privateKeyPem: string; keyId?: string; signedAt?: string }): object;
export function verifyPolicyPackSignature(manifest: object, signatureEnvelope: object, trustRoot: object): object;
export function signPolicyPackDirectory(directory: string, options: { privateKeyPem: string; keyId?: string; signedAt?: string; write?: boolean }): object;
export function verifyPolicyPackDirectory(directory: string, trustRoot: object): object;
export function verifyAllPolicyPackSignatures(policyPacksDir: string, trustRoot: object): object;
export function signEvidenceBundle(bundle: object, options: { privateKeyPem: string; keyId?: string; signedAt?: string }): object;
export function verifySignedEvidenceBundle(bundle: object, trustRoot: object): object;
export function signAuditEventChain(events: object[], options: { privateKeyPem: string; keyId?: string; signedAt?: string }): object;
export function verifyAuditEventChainSignature(events: object[], signatureEnvelope: object, trustRoot: object): object;
