export type ToolRisk = "low" | "medium" | "high" | "unknown" | "auto";
export type ToolDecision = "allowed" | "approval_required" | "blocked" | "unknown_action_requires_review";
export interface ToolDefinition { id?: string; name?: string; description?: string; kind?: string; risk?: ToolRisk; capabilities?: string[]; inputSchema?: unknown; metadata?: Record<string, unknown>; }
export interface ToolCall { requestId?: string; toolId?: string; tool?: string; name?: string; action?: string; subject?: string; actor?: string; inputPreview?: unknown; metadata?: Record<string, unknown>; }
export interface McpTool { name?: string; id?: string; description?: string; inputSchema?: unknown; annotations?: Record<string, unknown>; metadata?: Record<string, unknown>; }
export interface McpRequest { jsonrpc?: string; id?: string | number; method?: string; type?: string; params?: Record<string, unknown>; actor?: string; name?: string; arguments?: Record<string, unknown>; subject?: string; }
export class ToolManifest { constructor(args?: { tools?: ToolDefinition[]; metadata?: Record<string, unknown> }); static fromObject(value?: { tools?: ToolDefinition[]; metadata?: Record<string, unknown> }): ToolManifest; static fromFile(path: string): ToolManifest; static fromMcpServer(server?: Record<string, unknown>): ToolManifest; get(toolId: string): ToolDefinition | null; list(): ToolDefinition[]; }
export class ToolRiskClassifier { classify(tool?: ToolDefinition, call?: ToolCall): ToolRisk; defaultEffectForRisk(risk: ToolRisk): "allow" | "deny" | "approval_required"; }
export class ToolGuard { constructor(args?: { manifest?: ToolManifest | { tools?: ToolDefinition[] }; policy?: Record<string, unknown>; runId?: string; actor?: string; clock?: () => string }); evaluateToolCall(call: ToolCall): Record<string, unknown>; report(options?: { title?: string; summary?: string }): Record<string, unknown>; }
export class McpServerManifest { constructor(args?: { name?: string; version?: string; tools?: McpTool[]; resources?: unknown[]; prompts?: unknown[]; metadata?: Record<string, unknown> }); static fromObject(value?: Record<string, unknown>): McpServerManifest; static fromFile(path: string): McpServerManifest; toToolManifest(): ToolManifest; inspect(): Record<string, unknown>; }
export function normalizeMcpTool(tool?: McpTool): McpTool;
export class McpGuard { constructor(args?: { server?: Record<string, unknown>; manifest?: McpServerManifest; policy?: Record<string, unknown>; runId?: string; actor?: string }); static fromServerFile(path: string, options?: Record<string, unknown>): McpGuard; evaluateMcpToolCall(call: { name: string; arguments?: Record<string, unknown>; subject?: string; actor?: string; metadata?: Record<string, unknown> }): Record<string, unknown>; evaluateMcpRequest(request: McpRequest): Record<string, unknown>; evaluateBatch(requests: Array<McpRequest | { name: string; arguments?: Record<string, unknown> }>): Record<string, unknown>[]; inspect(): Record<string, unknown>; report(options?: { title?: string; summary?: string }): Record<string, unknown>; }

export declare class McpGuardProxy { constructor(args?: Record<string, unknown>); handleJsonRpc(request?: Record<string, unknown>): Promise<Record<string, unknown>>; handleBatch(requests?: Array<Record<string, unknown>>): Promise<Array<Record<string, unknown>>>; report(options?: Record<string, unknown>): Record<string, unknown>; }
